# Generated by Django 4.1.3 on 2023-11-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profile_image',
        ),
    ]
