# Generated by Django 4.1.3 on 2023-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0004_alter_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
