# Generated by Django 4.1.3 on 2023-11-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profileimg',
        ),
    ]
