# Generated by Django 4.1.3 on 2023-11-25 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0006_rename_profile_image_userprofile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blogmind.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileimg',
            field=models.ImageField(default='profile-1.jpg', upload_to='profile_images/'),
        ),
    ]
