# Generated by Django 4.1.3 on 2023-11-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0007_alter_post_image_alter_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
