# Generated by Django 4.1.3 on 2023-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogmind', '0009_alter_post_slug_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(default='profile-1.jpg', upload_to='profile_images/'),
        ),
    ]
